### ISSUE TITLE
No longer working in 9.96

### ISSUE THREAD

**Issue by raymondap** [brysontyrrell/StaticGroupFromSearch#4]
Thank you very much for this script.
I had to add after line 126 to get it working in the latest version of Casper suite. 
`request.add_header('Accept', 'application/xml')
`

**Comment by brysontyrrell** [comment]
@raymondap if you wanted to try it out, I'm now working on a series of functional and feature improvements to this utility. The first phase, replacing `urllib2` with `requests`, I just wrapped up and you can snag a copy here: a1eb75ef9d7f76c469497f7b6f3fb2299b2f0811

There are no new features in this commit, it will work the same as the version on `master`.

**Comment by cybertunnel** [comment]
This issue is also linked to issue #7
