### ISSUE TITLE
Issue with parsing XML

### ISSUE THREAD

**Issue by liamshanny** [brysontyrrell/StaticGroupFromSearch#7]
Any command I do results with the following error:

python StaticGroupFromSearch.py url "test" -u 'test' -p 'test' --computers --csv-file Workbook2.csv
performing search on the JSS at: ../JSSResource/computers/match/lshanny2-mac
Traceback (most recent call last):
  File "StaticGroupFromSearch.py", line 206, in <module>
    main()
  File "StaticGroupFromSearch.py", line 185, in main
    results = jss.get_match(value)
  File "StaticGroupFromSearch.py", line 116, in get_match
    return etree.fromstring(self.request(request))
  File "<string>", line 124, in XML
cElementTree.ParseError: not well-formed (invalid token): line 1, column 0

JSS version: 10.1.1-t1513360285
Python: 2.7.14

Tried different ways to save the CSV file, different args, including the examples provided, and a different API account. All give me the same issue.

**Comment by cybertunnel** [comment]
Found the issue you described, and is fixed in my PR. The data returned wasn't XML data _all_ the time, so I added the `accept: text/xml` header to specifically tell the server to return XML data.
